apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
  namespace: bookinfo3 
spec:
  host: productpage
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: bookinfo3.apps.myazure.online
